import Head from "next/head";
import "@/src/styles/globals.css";
import { useCounter } from "@/src/hocks/useCounter";
import { useInputArray } from "@/src/hocks/useInputArray";
import { useEffectBG } from "@/src/hocks/useEffectBG";

export default function App({ Component, pageProps }) {
  const counter = useCounter();
  const inputArray = useInputArray();

  useEffectBG();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...counter} {...inputArray} />
    </>
  );
}
